export const FAILED_TO_CREATE_PROJ_DOCKDEV_DIR = 'FAILED_TO_CREATE_PROJ_DOCKDEV_DIR';
export const FAILED_PROJECT_WRITE = 'FAILED_PROJECT_WRITE';
export const FAILED_ADD_PROJ_TO_CONFIG = 'FAILED_ADD_PROJ_TO_CONFIG';
export const FAILED_READ_CONFIG = 'FAILED_READ_CONFIG';
