export const EEXIST = 'EEXIST';

// DockDev messages
export const FAILED_TO_ACCESS_MACHINE = 'FAILED_TO_ACCESS_MACHINE';

export const FAILED_TO_CREATE_PROJ_DOCKDEV_DIR = 'FAILED_TO_CREATE_PROJ_DOCKDEV_DIR';
export const FAILED_TO_CREATE_CONFIG_DIR = 'FAILED_TO_CREATE_CONFIG_DIR';
export const FAILED_PROJECT_WRITE = 'FAILED_PROJECT_WRITE';
export const FAILED_ADD_PROJ_TO_CONFIG = 'FAILED_ADD_PROJ_TO_CONFIG';
export const FAILED_READ_CONFIG = 'FAILED_READ_CONFIG';
export const FAILED_TO_WRITE_CONFIG = 'FAILED_TO_WRITE_CONFIG';
export const FAILED_TO_START_CONTAINER = 'FAILED_TO_START_CONTAINER';
export const FAILED_TO_STOP_CONTAINER = 'FAILED_TO_STOP_CONTAINER';
export const FAILED_TO_INSPECT_CONTAINER = 'FAILED_TO_INSPECT_CONTAINER';
export const FAILED_TO_LIST_CONTAINERS = 'FAILED_TO_LIST_CONTAINERS';
export const FAILED_TO_CREATE_CONTAINER = 'FAILED_TO_CREATE_CONTAINER';
export const FAILED_TO_RESTART_CONTAINER = 'FAILED_TO_RESTART_CONTAINER';
export const FAILED_TO_REMOVE_CONTAINER = 'FAILED_TO_REMOVE_CONTAINER';
export const FAILED_TO_GET_IMAGES = 'FAILED_TO_GET_IMAGES';
export const FAILED_TO_CREATE_NETWORK = 'FAILED_TO_CREATE_NETWORK';
export const FAILED_TO_INSPECT_NETWORK = 'FAILED_TO_INSPECT_NETWORK';
export const FAILED_TO_DELETE_NETWORK = 'FAILED_TO_DELETE_NETWORK';
export const PROJECT_NAME_EXISTS = 'PROJECT_NAME_EXISTS';
export const PROJECT_DIR_USED = 'PROJECT_DIR_USED';
export const FAILED_TO_READ_PROJECT = 'FAILED_TO_READ_PROJECT';
export const FAILED_TO_UPDATE_DOTOKEN = 'FAILED_TO_UPDATE_DOTOKEN';
export const FAILED_TO_CREATE_DOCKERFILE = 'FAILED_TO_CREATE_DOCKERFILE';
export const FAILED_TO_SYNC_TO_REMOTE = 'FAILED_TO_SYNC_TO_REMOTE';
export const FAILED_TO_BUILD_SERVER_IMAGE = 'FAILED_TO_BUILD_SERVER_IMAGE';
export const NO_DOTOKEN = 'NO_DOTOKEN';
